### ISSUE TITLE
Explicit interproscan output and small fix in function description

### ISSUE THREAD

**Issue by SantosRAC** [sepro/CoNekT#12]
Hi @sepro ,

I am adding InterPro annotation to our instance (InterProScan results).
Just a suggestion: to add the specific Interproscan output format (TSV) to the page describing how to [add gene functional information page](https://github.com/sepro/CoNekT/blob/master/docs/building/002_species_functional_data.md).

Just a small fix. Found "Adds GO annotation from InterProScan Output" as description of the "add_interpro_from_interproscan" function. The correct is "Adds Interpro", right? ("add_go_from_tab" adds GO from tab).

Cheers,
Renato Santos.

**Comment by sepro** [comment]
Feel free to improve the docs as you make your way through them and create a pull request. I'll review PRs but don't have the bandwidth to iterate over these myself.

**Comment by SantosRAC** [comment]
Thanks, @sepro ! I will do it then. :)
