### ISSUE TITLE
Unable to install requirements (OSX/M1)

### ISSUE THREAD

**Issue by 107laserfish** [sepro/CoNekT#16]
**Describe the bug**
Unable to install requirements.

**To Reproduce**
Attempted to set up CoNekT with my device following the installation instructions but leads to error when trying to install requirements "ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects"

**Expected behavior**
Expected to install requirements. 

**Screenshots and stacktrace**
<img width="859" alt="image" src="https://user-images.githubusercontent.com/34560154/193217771-1311d107-1f4e-487a-858f-77ece0d6378a.png">

**Details about your system:**
 - OS: Mac OS 12.4; Macbook Air M1

**Comment by sepro** [comment]
Which version of Python was used here?

**Comment by 107laserfish** [comment]
Hello! It was on 3.9 but I tried 3.6.10 using pyenv and got the same results. On 30 Sep 2022, at 9:31 PM, Sebastian Proost ***@***.***> wrote:﻿
Which version of Python was used here?

**Comment by sepro** [comment]
As unit-tests run fine on 3.9 this must be an OSX or M1 specific issue. Unless someone donates me a MacBook I can't replicate and fix the issue I'm afraid.

**Comment by sepro** [comment]
@107laserfish can you check if [this](https://community.home-assistant.io/t/error-failed-building-wheel-for-cryptography/352020/5) solution works? 

Binary wheel for the M1 doesn't exist and needs to be compiled. Which requires Rust, setting ```export CRYPTOGRAPHY_DONT_BUILD_RUST=1``` should avoid that issue for this package. However, this might be an issue on the M1 for other dependencies.

**Comment by 107laserfish** [comment]
Hello @sepro! Sorry for the late reply. 
I tried this solution but it did not work. However, I managed to get it running but setting the requirements for cffi, cryptography, and all other Flask libraries to the newest available version (<=). I understand conventionally we do not need to touch these but perhaps they need to be updated for working with M1 devices. 
Thanks for your help!

**Comment by sepro** [comment]
Glad it works now ! OSX never was supported and CoNekT predates the M1, so it is great it is possible to run it on those systems, it never was in scope of this project to support that OS and devices. Spending time adding support now would require updating all dependencies. To ensure nothing breaks, this would require the coverage of the unit tests to be expanded to a fairly high coverage. (or do a thorough test with a comprehensive dataset afterwards) Which requires far more time than I can currently justify spending on this project.
