### ISSUE TITLE
ZeroDivisionError when attempting to reconcile trees

### ISSUE THREAD

**Issue by 107laserfish** [sepro/CoNekT#17]
**Describe the bug**
I'm adding some species to a database with about 20+ species and I've uploaded gene families and trees from OrthoFinder's output, but I'm unable to reconcile trees as that gives me a ZeroDivisionError ([reconcile trees error.pdf](https://github.com/sepro/CoNekT/files/10342353/reconcile.trees.error.pdf)). My OrthoFinder files are zipped as specified in the instructions so I'm not very sure what's the issue. I've tried deleting previously uploaded trees but that gives me an InternalError ([delete trees error.pdf](https://github.com/sepro/CoNekT/files/10342355/delete.trees.error.pdf)).

**To Reproduce**
I'm following [these steps](https://github.com/sepro/CoNekT/blob/master/docs/building/005_comparative_genomics.md) to upload my files. 

**Screenshots and stacktrace**
Error when trying to reconcile new trees
<img width="858" alt="image" src="https://user-images.githubusercontent.com/34560154/210509914-e9d32127-53cd-43ea-b9cf-895c3fb4aede.png">

Error when deleting previous trees
<img width="861" alt="image" src="https://user-images.githubusercontent.com/34560154/210509779-2c7a6603-2590-485c-8046-c4cc2c3b3aa3.png">

[reconcile trees error.pdf](https://github.com/sepro/CoNekT/files/10342353/reconcile.trees.error.pdf)
[delete trees error.pdf](https://github.com/sepro/CoNekT/files/10342352/delete.trees.error.pdf)

**Details about your system:**
   
 - Python version: 3.7.6
 - OS: Windows
 - Database: MaraiDB/MySQL

**Comment by sepro** [comment]
Can you try creating ortho-groups and trees for a subset of species and check if this works/fails? (2-3 species)

Check you have the correct version of OrthoFinder, only v1.1.x is supported.

**Comment by sepro** [comment]
This issue likely stems from adding trees which are too large during the previous step, resulting in incomplete newick strings in the database. These can be removed prior to uploading trees.

**Comment by sepro** [comment]
As no further information was provided I'll assume this was indeed a set with trees too large for the database to store properly and close the issue.

**Comment by SantosRAC** [comment]
Hi @sepro , I hope you are well.

Regarding OrthoFinder 1.1.x, I think one limitation today (that I am aware of) is that it uses dlcpar (which generates the input required in CoNekT). dlcpar uses Python 2. Recently I tried to install it and I was not able to run OrthoFinder 1.1.x due to incompatibilities with my environment that uses Python 3 for almost everything.

If possible, it would be nice if you could add one or a few trees in the `tests/data` folder (this would help when making adaptations to a newer version of CoNekT).

Let me know if you are aware of anyone working on adaptations of CoNekT to handle trees produced by OrthoFinder 2. Of course, I would love to contribute.

Regards from Brazil
Renato

**Comment by SantosRAC** [comment]
Just to let you know I downloaded Newick, XML, and ASCII from the instance currently active! Assuming the Newick downloaded is the same as the one generated with dlcpar in OrthoFinder 1, this would be enough! Thanks a lot in advance.

**Comment by SantosRAC** [comment]
If others have the same questions, I'm just referencing your (@sepro ) previous comment on another issue here: https://github.com/sepro/CoNekT/issues/3#issuecomment-473842072

**Comment by sepro** [comment]
The generic importer has been reported to work with OrthoFinder 2 and was used for [a legume based CoNekT](https://github.com/legumeinfo/ConektLegumes).
