### ISSUE TITLE
Reconcile Trees - Data too long and MySQL server has gone away errors

### ISSUE THREAD

**Issue by jonng2018** [sepro/CoNekT#5]
When reconciling trees in the "Build" tab the follow errors are encountered.
`sqlalchemy.exc.dataerror...."Data too long for column 'data_phyloxml' at row 1"`
![recon_trees_error_140319](https://user-images.githubusercontent.com/34784455/54409587-85c12a80-4722-11e9-95a6-8ec0f0fe96bc.png)

This could be because `db.Text` is used (shown below), which uses mysql `TEXT` type, but `LONGTEXT` (or `MEDIUMTEXT` ?) should be used instead
![phyloxml](https://user-images.githubusercontent.com/34784455/54409659-f5371a00-4722-11e9-8fa6-ea0d7b078195.png)

**Question 1) How do I change `TEXT` to `LONGTEXT?` I tried using:**
`db.LONGTEXT`
`db.LongText`
`db.LongTexT`

But see errors like:
```
Detected change in 'D:\\GoogleDrive\\Conekt_db\\CoNekT\\conekt\\models\\trees.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    app = create_app('config')
  File "D:\GoogleDrive\Conekt_db\CoNekT\conekt\app.py", line 32, in create_app
    configure_blueprints(app)
  File "D:\GoogleDrive\Conekt_db\CoNekT\conekt\app.py", line 100, in configure_blueprints
    from conekt.controllers.heatmap import heatmap
  File "D:\GoogleDrive\Conekt_db\CoNekT\conekt\controllers\heatmap.py", line 12, in <module>
    from conekt.models.trees import Tree
  File "D:\GoogleDrive\Conekt_db\CoNekT\conekt\models\trees.py", line 116, in <module>
    class Tree(db.Model):
  File "D:\GoogleDrive\Conekt_db\CoNekT\conekt\models\trees.py", line 122, in Tree
    data_phyloxml = db.Column(db.LongTexT)
 AttributeError: 'SQLAlchemy' object has no attribute 'LongText'` 
```

I then went to MariaDB and did:
`MariaDB [diurnal]> ALTER TABLE trees
 -> MODIFY data_phyloxml LONGTEXT;`

Which was successful:
```
Query OK, 14290 rows affected (4.588 sec)
Records: 14290  Duplicates: 0  Warnings: 0

MariaDB [diurnal]> DESCRIBE trees;
+---------------+-------------+------+-----+---------+----------------+
| Field         | Type        | Null | Key | Default | Extra          |
+---------------+-------------+------+-----+---------+----------------+
| id            | int(11)     | NO   | PRI | NULL    | auto_increment |
| label         | varchar(50) | YES  | MUL | NULL    |                |
| data_newick   | text        | YES  |     | NULL    |                |
| data_phyloxml | longtext    | YES  |     | NULL    |                |
| gf_id         | int(11)     | YES  | MUL | NULL    |                |
| method_id     | int(11)     | YES  | MUL | NULL    |                |
+---------------+-------------+------+-----+---------+----------------+
6 rows in set (0.011 sec)
```

However, after I reconciled trees, I have this error:
![tmeout](https://user-images.githubusercontent.com/34784455/54409947-4693d900-4724-11e9-80ee-bede3c852620.png)

**Question 2) How do I resolve this?**
This seems like a timeout error, possibly because my Conekt has 17 species, hence their trees have a lot of data, which could account for the problem in question 1, and the transmitted packets could be very large, exceeding the max packet size, and hence causing this timeout error.

I did the following in MariaDB:
```
show variables like 'max_allowed_packet';
 max_allowed_packet | 10485760
SET GLOBAL max_allowed_packet=1073741824;
```
Closed MariaDB and opened it again
```
show variables like 'max_allowed_packet';
 max_allowed_packet | 1073741824
```

This set the packet size to the max of 1GB, and am reconciling trees.

Please let me know if this solution makes, or if there's another way to solve this. Also, please advise on how to change Conekt settings to reflect this (if these steps are indeed correct), so that the user does not need to manually change them whenever Conekt is installed/restarted.

Thanks!

Update 170319:
This solution doesn't work as I still get the `MySQL server has gone away` error. Please advise on how to solve it.

**Comment by sepro** [comment]
a) Trees need to be kept within reasonable limits. The largest tree in the public version contains 282 items (and fits well within the 65k character limit of the default text) and is barely usable using the current viewer. Large trees can simply be excluded from the .tar.gz file when uploading the data and plenty of options are available when leveraging CoNekT's capabilities to include multiple methods for constructing gene families/trees to work around this limit. 

b) Changing the database structure without making the corresponding change to the model is a recipe for trouble. Flask-Sqlalchemy doesn't support MySQL/MariaDB specific column types, so if you do decide to further attempt this, contact the author for that package on tips how to achieve this.

c) There isn't enough information here what is causing the SQL related issues as the stacktrace is clipped and doesn't show the relevant point of the code. Though when taken point a + b into account this likely is no longer relevant.
