### ISSUE TITLE
Can I just do all the analysis on linux? How?

### ISSUE THREAD

**Issue by ShuaiNIEgithub** [sepro/CoNekT#6]
hello!
I liked the tool as soon as I noticed it, and I couldn't wait to try to install it on the linux platform.
However, I only saw the detailed tutorial for windows, but did not find the tutorial on linux.
So, could you give a more detailed tutorial for my own species? I am not familiar with flask.
Thanks a million!

**Comment by sepro** [comment]
There are instructions how to install CoNekT locally on a linux system available [here](https://github.com/sepro/CoNekT/blob/master/docs/install_linux.md). 

Once installed you should follow the instructions in the section [building CoNekT](https://github.com/sepro/CoNekT/blob/master/docs/building_conekt.md). This section is entirely platform independent and will work on both Linux and Windows.

**Comment by ShuaiNIEgithub** [comment]
That's great, I will try it
Thank you a lot!

--------------原始邮件--------------
发件人："Sebastian Proost "<notifications@github.com&gt;;
发送时间：2020年2月29日(星期六) 晚上11:14
收件人："sepro/CoNekT" <CoNekT@noreply.github.com&gt;;
抄送："ShuaiNIEgithub "<nieshuai@bjfu.edu.cn&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [sepro/CoNekT] Can I just do all the analysis on linux? How? (#6)
-----------------------------------

 
There are instructions how to install CoNekT locally on a linux system available here.
 
Once installed you should follow the instructions in the section building CoNekT. This section is entirely platform independent and will work on both Linux and Windows.
